### PR TITLE
Add PBR documentation

### PR DESCRIPTION
**Pull request by Equalizer5118**
Moving from old PR as PBR documentation is more modern than old workshop.

### CODE REVIEW

**Comment by ozxybox** [comment]
Looking good so far! I think you’ll want to edit the meta.json file to get the topic to show up on the web page though. You can see in the above cloud flare link what it would look like live. You can reference how it’s done for the `util` topic. If you get confused with it, I can help. (Maybe we need to make this easier to as new topics? lol)

I’ll try to get one of our artists to provide some quick review if possible.

Thanks!!

**Comment by November-N** [comment]
said artist here, information seems accurate. maybe you could change some of the language a bit to clarify (specify normal maps specifically instead of bumpmaps which could include SSBumps which aren't supported), but it seems accurate and good for a base

**Comment by ozxybox** [comment]
Looks like the meta.json was solid, and the content deployed out to a test page successfully!

https://equalizer5118-patch-2.wiki-5tv.pages.dev/shared/reference/PBR/materialcreation

**Comment by Equalizer5118** [comment]
Alright, finished with PBR docs. All images work, all links work, I'm satisfied

**Comment by ozxybox** [comment]
Thanks for all the solid docs! Hope you don't mind me tacking on a little fixup commit here. 

Now that we're starting to get some proper documentation, I'm realizing that our custom generator software needs a bit of work! Haha

**Review by ozxybox — APPROVED** [review]

**Comment by Maxkatsur** [comment]
This documentation looks better now. Documentation may be boring, but it needs to be informative, relevant and accurate to the very specific subject matter (and, potentially, sub-topics). No bias, no confusion, no lies.

**Pull request merged**
